spring:
  profiles:
    active:
    - dev

---

server:
  port: 8001
  
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: dbc:mysql://localhost:3306/springcloud01 
    username: root
    password: root
    dbcp2:
      min-idle: 5   
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: org.bigjava.springcloud.bean    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                   # mapper映射文件
  
eureka:
  client:  #将客户端注册进eureka服务列表中
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003com:7003/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true    #显示ip  
    
info:
  app-name: bigjava-microservicecloud
  company.name: www.bigjava.com
  bulid.artifactId: $project.artifactId$
  bulid.version: $project.version$ 
  
---

server:
  port: 8001
  
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: dbc:mysql://localhost:3306/springcloud01 
    username: root
    password: root
    dbcp2:
      min-idle: 5   
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: org.bigjava.springcloud.bean    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                   # mapper映射文件
  
eureka:
  client:  #将客户端注册进eureka服务列表中
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003com:7003/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true    #显示ip  
    
info:
  app-name: bigjava-microservicecloud
  company.name: www.bigjava.com
  bulid.artifactId: $project.artifactId$
  bulid.version: $project.version$                      