spring:
    profile:
      active: 
      - dev
        
---

server:
    port: 8201
    
spring: 
    application: 
        name: microservicecloud-config-client
    profile: dev
    
eureka:
    client: 
        service-url: 
            defaultZone: http://eureka-dev.com:7001/eureka/
            
---

server:
    port: 8202
    
spring: 
    application: 
        name: microservicecloud-config-client
    profile: test
    
eureka:
    client: 
        service-url: 
            defaultZone: http://eureka-test.com:7001/eureka/
    